import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {makeStaticPaths, makeStaticProps} from '../../lib/getStatic'
//import { useTranslation } from 'next-i18next'
import {getContent} from "../../utils/getContent";

export async function getStaticProps(ctx) {
  const {data} = await getContent({path_file: `/content/test/${ctx.params.locale}.md`});
  return {
    props: {
      ...makeStaticProps(['common', 'footer']),
      data
    }
  }
}

export async function getStaticPaths() {
  return {
    ...makeStaticPaths(),
  };
}
export default function Test({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          {data.title}
        </h1>
      </main>
    </div>
  )
}
